# Generated by Django 5.0.1 on 2024-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Christcourier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_admin',
        ),
        migrations.DeleteModel(
            name='New_staff',
        ),
    ]
