# Generated by Django 5.0.1 on 2024-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Christcourier', '0002_delete_new_admin_delete_new_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_date', models.DateField()),
                ('p_ser', models.CharField(choices=[('amazon', 'amazon'), ('flipkart', 'flipkart'), ('myntra', 'myntra'), ('nykaa', 'nykaa'), ('meesho', 'meesho'), ('others', 'others')], max_length=200)),
            ],
        ),
    ]
    
