# Generated by Django 5.0.1 on 2024-02-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Christcourier', '0003_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='p_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='p_otp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
